### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#10]
I have few questions and don't know better place where to ask.

1. `type Char = c8|c32 c`:

 Is this union like in C, without any hidden tag? How are ambiguities resolved? Say:

 ```
 type foo = i8 | i16
 var foo  bar = i8 10
 var i32 baz  = bar
 ``` 

2. ranges:

 ```
 for u in 0 ..^ testArr.len() do
     print(testArr#u)
 ```

 Will the `testArr.len()` be called repeatedly or will the compiler inspect the body of `for` and move it out?

3. Type condition errors:

 ```
 type Teen =
     u8 age  in 10 .. 19
     Str name  where name.length > 0
 //TypeConditionErr
 let sara = Teen(18, "")
 ```

 If the condition is not true during runtime what will happen?  Is/will there be some way to disable the check either explicitly or because some checking actions made before?

 In `language.am` there's sentence "TypeConditionErr is thrown". I though exceptions are not in the language.

**Comment by jfecher** [comment]
1.  Such a union is just shorthand for a normal union with a tag, just replacing what would normally be a unique tag name with the type name of the type it contains, eg.
```
//Typenames must be capitalized
type Foo = i8 | i16

let Foo x = 0_i16

Ante.dump x
```
outputs:
```
%i = {i8, i16} {i8 1, i16 0}
```
Where the first value is the implicit tag, and the second is the C union that is represented as the largest union member's type (and because the compiler always has access to the tag, there is no ambiguity).

2.  In the case you provided, it would only be called once because the range created by ..^ is immutable.  This behaviour can be changed by overloading the .. operator for any given type.

3.  If compiled in debug mode, and the condition is not met, the program will give an error message for the given type condition.  If compiled in release mode, this check is removed, although I may change this to favour safety and keep in the check, but without the src information so the user does not see the source code in an enterprise program.

Also, the file is `language.an` all Ante src files have the `.an` suffix

**Comment by PavelVozenilek** [comment]
About the unions: I used them (1) to get easy access to bytes representing some data, (2) to do endian conversion and (3) to deal with poorly designed Win32 high-perf timer API. 

It feels that compiler enforced tagged unions will not allow anything like that.

**Comment by jfecher** [comment]
You are correct, they will not.  Such bit-level operations are performed by type-casting the desired data to a `BitArray` and working on it from there.
