### ISSUE TITLE
Generic Int types default to i32 too early

### ISSUE THREAD

**Issue by ehllie** [jfecher/ante#130]
```scala
type Generator a =
  endo: a -> a
  seed: a

impl Iterator (Generator a) a with
    next gen =
      endo, seed = gen.endo, gen.seed
      new = endo seed
      Some (Generator endo new, seed)

type TakeWhile i a =
  pred: a -> bool
  iter: i

impl Iterator (TakeWhile i a) a given Iterator i a with
    next tw =
      match next tw.iter
      | Some (iter, new) ->
          if tw.pred new
          then Some (TakeWhile tw.pred iter, new)
          else None
      | None -> None

i = TakeWhile (fn x -> x < 1000) (Generator (fn x -> x * 2) 1u64)

iter i print
```
This code fails to run, because the type of i gets inferred to `(TakeWhile (Generator u64) i32)` even though the predicate lambda `fn x -> x < 1000` should be compatible with any integer type.

**Comment by ehllie** [comment]
Possibly related to #129

**Comment by jfecher** [comment]
I've determined the cause of this error:
- There are 2 constraints being solved at the same time:
  1. The `Int x` originating from `(fn x -> x * 2) : x -> x given Int x, Mul x`
  2. The `Iterator (TakeWhile (Generator u64) x) x` constraint that is currently failing to be found.

What is happening currently is that Int constraints are filtered out and solved first since they may affect future constraints if they bind a type to `i32`. Here this behavior is causing the later constraint to fail since it sees `i32` now instead of a generic type variable.

I don't have a solution at the moment however. Simply disabling the Int filtering or reversing it such that it filters last may not be a solution since it may break other code that relies on it to filter first (e.g. Cast constraints looking at specific integer types). I'll experiment with a hybrid of what ante used to do with a "2 rounds" approach - basically if a trait failed to find an instance it'd try again until it made no progress in case any later trait impls bind any types. It may be that we need to filter Int constraints to be done last, then also retry any failing constraints again after these. So the flow would be:

```hs
failing_constraints = try_solve constraints
try_solve int_constraints

while not is_empty failing_constraints do
    prev_len = len failing_constraints
    failing_constraints := try_solve failing_constraints
    if len failing_constraints == prev_len then
        error ....
```

**Comment by ehllie** [comment]
This is solved, but I still had one thing to add here. I initially thought this might be related to HKT, since that's how the equivalent of this code would look in haskell:

```haskell
class Iterator i where
  next :: i a -> Maybe (a, i a)

iter :: Iterator i => i a -> (a -> b) -> [b]
iter i f = case next i of
  Nothing -> []
  Just (a, i') -> f a : iter i' f

data Generator a = Generator (a -> a) a

data TakeWhile i a = TakeWhile (a -> Bool) (i a)

instance Iterator Generator where
  next (Generator f a) = Just (a, Generator f (f a))

instance Iterator i => Iterator (TakeWhile i) where
  next (TakeWhile p i) = case next i of
    Just (a, i') -> if p a then Just (a, TakeWhile p i') else Nothing
    Nothing -> Nothing

i = TakeWhile (< 1000) (Generator (* 2) 1)

main = sequence_ $ iter i print
```
Notice how the kind of `i` in both `Iterator` and `TakeWhile` is `* -> *`. Maybe "a better way" to handle this would be HKT since those would indicate relationships between recursive constraints?

**Comment by jfecher** [comment]
Even in haskell I tend to reach for multi parameter typeclasses over HKT when using typeclasses since they're more flexible. E.g. this iterator design requires the iterator type to be parameterized over an element type which wouldn't work for iterating over Bytes in a Bytestring, among other cases.

This style should be semi-supported in ante although currently there is no way to partially apply type constructors so the `(TakeWhile i)` here isn't possible. For reference I converted the above snippet to:
```scala
trait Iterator2 i with
    next2: i a -> Maybe (i a, a)

iter2 (i: i a) (f: a -> b) : unit = 
    match next2 i
    | None -> ()
    | Some (i2, a) -> 
        f a
        iter2 i2 f

type Generator a = 
    f: a -> a
    e: a

type TakeWhile i a =
    f: a -> bool
    iter2: i a

impl Iterator2 Generator with
    next2 gen = 
        f, a = gen.f, gen.a
        Some (Generator f (f a), a)

impl Iterator2 (TakeWhile i) given Iterator2 i with
    next2 tw = 
        f, it = tw.f, tw.iter
        match next2 it
        | Some (i2, a) -> if f a then Some (TakeWhile f i2, a) else None
        | None -> None

i = TakeWhile (_ < 1000) (Generator (_ * 2) 1)

iter2 i print
```
and it gives these errors:
```
?master ~/Code/Ante/ante> ante t.an
t.an:21:5       error: variable type ({ a: b, f: (b -> b can c), .. } -> (Maybe ((Generator b), b)) can c) does not match its declared type of ((Generator a) -> (Maybe ((Generator a), a)) can b)
    next2 gen =

t.an:26:5       error: variable type ({ f: (b -> bool can c), iter: (d b), .. } -> (Maybe ((TakeWhile d b), b)) can c) does not match its declared type of (((TakeWhile a) b) -> (Maybe (((TakeWhile a) b), b)) can c)
    next2 tw =

t.an:34:7       error: Expected argument of type (a b), but found (TakeWhile Generator a)
iter2 i print

t.an:34:1       error: 2 matching impls found for Iterator2 a
iter2 i print

t.an:20:1       note: Candidate 1
impl Iterator2 Generator with

t.an:25:1       note: Candidate 2
impl Iterator2 (TakeWhile i) given Iterator2 i with

t.an:34:9       error: 15 matching impls found for Print a
iter2 i print

/.../ante/stdlib/prelude.an:356:1        note: Candidate 1
impl Print u8  with printne x = print_unsigned (cast x)

/.../ante/stdlib/prelude.an:357:1        note: Candidate 2
impl Print u16 with printne x = print_unsigned (cast x)

/.../ante/stdlib/prelude.an:358:1        note: Candidate 3 (12 more hidden)
impl Print u32 with printne x = print_unsigned (cast x)
```
