### ISSUE TITLE
Windows port?

### ISSUE THREAD

**Issue by PavelVozenilek** [jfecher/ante#14]
Do you have a plan to port Ante on Win32? Is there something where I could help? I would try myself, but I read such horror stories about LLVM ...

**Comment by jfecher** [comment]
I have successfully compiled the compiler itself on mingw, but had some errors with llvm.  I havent pursued it much further since then, but I can look into it some more.

**Comment by PavelVozenilek** [comment]
> had some errors with llvm

Uhh, so the rumors were right ...

**Comment by jfecher** [comment]
After some trial and error I added a windows binary of the current release; unfortunately due to some issues with llvm assertions being compiled in, it does not seem to work with llvm v3.9.1

**Comment by PavelVozenilek** [comment]
This is like Chrismas gift!

I tried Hello world and found:

1. It has hardcoded path to standard library to  `'C:\Program Files (x86)\Ante\prelude.an'`. On Win7 this directory is protected, one has to make the directory and copy the file there as administrator.

2. I tried to compile this:

   ```
   print "Hello World!\n"
   ```

   and got following error:

    ```
      O:\ante\ante-master\bin>ante a.an
      Assertion failed: V[I]->getType() == T->getTypeAtIndex(I) && "Initializer for composite element doesn't match!", file C:
      \llvm_src\lib\IR\Constants.cpp, line 883

      O:\ante\ante-master\bin>
     ```

**Comment by jfecher** [comment]
yeah I just changed the lib dir to a place i would put mine on windows.  in the future when there is an installer this can be changed.  I'm also adding some #define guards in the next patch so that if you want if you're compiling from source you can specify the AN_LIBDIR to install to via a flag passed to the c++ compiler used.

The following error you got is the same one I was stuck with though, I looked it up and found an llvm bug report on it, saying it was fixed in a previous release.  It should be something to do with llvm being compiled in debug mode with assertions on in some sections and ante itself not compiled in debug mode.

Thank you for testing it, I can at least now confirm that llvm was in fact statically linked.

**Comment by jfecher** [comment]
With commit 6035a82 it is apparent a windows port may take more time than initially thought.  The crux of the problem seems to be windows has its own idea of allocating memory, seemingly crashing programs at random deallocations that _should_ otherwise be safe.  I'm still not quite sure if its a problem with my configuration of llvm or the ante frontend itself.

**Comment by PavelVozenilek** [comment]
Memory management on Windows is all but ordinary, unless you play some strange tricks with VirtualAlloc family of functions. You may try Doug Lea's malloc ( http://g.oswego.edu/dl/html/malloc.html ), it can replace malloc/free and can be configured to do a lot of runtime checking.

**Comment by jfecher** [comment]
The compiler itself does not odd memory tricks, but upon further analysis it seems that once again, llvm is most likely the problem.

**Comment by jfecher** [comment]
The windows executable now works with the latest stable version.

Note that it requires you to have a compatible linker installed in the directory C:\MinGW\bin\gcc.exe
If you already have a c++ compiler you can copy (and rename it) to that directory for now.  If you cannot find a linker on your system, you can install MinGW to that directory.

**Comment by PavelVozenilek** [comment]
I downloaded zipped project, made sure mingw (64 bit) is on the correct path and tried Hello World.

The result:

```
O:\ante\ante-master\bin>ante hello.an
Assertion failed: V[I]->getType() == T->getTypeAtIndex(I) && "Initializer for composite element doesn't match!", file C:
\llvm_src\lib\IR\Constants.cpp, line 883

O:\ante\ante-master\bin>

```

**Comment by jfecher** [comment]
...I may have copied the wrong executable, I'll upload the new one real quick.

**Comment by PavelVozenilek** [comment]
_This time_ it got through!

When I use some old 32 bit mingw it compiles and generates executable which prints "Hello World!\n". I'll play with it and possibly report problems or suggestions.


When I tried Mingw64 I got this error:
```
O:\ante\ante-master\bin>ante hello.an
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.1/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input f
ile `hello.o' is incompatible with i386:x86-64 output
hello.o:(.text+0x25): undefined reference to `_puts'
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.1/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32
_a-crt0_c.o):crt0_c.c:(.text.startup+0x2e): undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status

O:\ante\ante-master\bin>

```

It could be some mess on my side, though ...

**Comment by jfecher** [comment]
The executable currently only generates 32-bit executables on windows due to llvm apparently not being able to detect if windows is 64 bit.
