### ISSUE TITLE
String length overriding tuple in union

### ISSUE THREAD

**Issue by ivanbakel** [jfecher/ante#40]
Using the same code as #39 , but replacing with a tuple match and extract:

Printing the value of the `u8` in `Some` always gives the length of the string, and not the value passed in to the constructor.

**Comment by jfecher** [comment]
Can I see your code?  I am using the following and am getting the correct output of 1 and Test:
```
type MaybeIntStr =
   | Some u8, Str
   | None

fun printmis: MaybeIntStr m
    match m with
    | Some t -> printf "%d and %s\n" (t#0) (t#1); ()
    | None -> print "None"

let s = Some(1u8, "Test")
printmis s
```
The `; ()` after the printf is just to satisfy the typecheck of the match branches so they all return void

**Comment by ivanbakel** [comment]
The key difference is that I did `"%s and %d\n" (t#1) (t#0)` instead. This looks like the `%d` is taking from the `Str` the first time. `"%s and %d and %d\n"` prints the length followed by `t#0`.

**Comment by jfecher** [comment]
printf expects a c-string, and the Str datatype is a c-string and its length.  Instead of `t#1` use `t#1#0` or the equivalent `(t#1).cStr`

**Comment by ivanbakel** [comment]
Shouldn't printf consider `Str` a single type instead of auto-expanding the tuple?

**Comment by jfecher** [comment]
Str is a tuple type, it does not need to be auto expanded.  Ante passes arguments by value by default so it passes the entire (c8*, u32) that is a Str.  There is no auto-expanding step, the address a tuple is stored at is the same as the address of its first member type, theres no poimter indirection or anything.  The odd behaviour is caused by the lack of type safety C's printf function provides, without specific compiler support it has no idea you mistakenly passed a tuple to it instead of a pointer.

**Comment by jfecher** [comment]
After writing all that out it occurred to me that you probably meant to ask why the implementation details of printf cause it to take the u32 len of the Str as the %d term instead of the passed u8.  This is most likely because printf uses va_arg to increment to the next parameter.  va_arg does this by taking the the type in question and increments it by the size of the type.  Since printf thinks the Str is just a c8*, it only increments it by that amount and ends up on the second member of the tuple instead of the u8 following it.  This is all because varargs are contiguous in memory.
