### ISSUE TITLE
Adding some examples

### ISSUE THREAD

**Issue by codec-abc** [jfecher/ante#55]
Hi,

This project looks interesting and the site is pretty great and give some information about the language. However there are few things that are missing and as such it would be great if there more examples. Among other things I would like to know more about memory management (The site speak about the `import gc` statement but I couldn't find any example to illustrate it). Also I wonder what is the error model (exception?, sum type?, ...). Also the factorial example in the web site has a type `Nat` that appear nowhere else.

So maybe a few example program of maximum 100 lines doing trivial things (like doing a command line "guess the number game", opening a text file and counting the vowels, etc..) might be added to the repository (or even better to the integration test) to showcase the language.

**Comment by jfecher** [comment]
The website shows the language but not all language or library features are implemented into the compiler yet.  The `GC` module for example is not yet implemented.  I have been needing to add a section about it on the website and will probably add one sometime soon.  To answer your other question, Ante uses sum types for error handling and exceptions are not in the language.  Currently the only type used for this is `Maybe 't`.  A type similar to rust's `Result<T, E>` can be implemented easily, there is just no need for it in the standard library yet.

I have a few example Ante programs lying around my computer I can upload to the integration tests, including a guess the number game.  There is also my [connect4](https://github.com/jfecher/connect4) program which is ~200 lines already on github.

**Comment by codec-abc** [comment]
Thanks for the answer. Before closing this issue, Can you elaborate a bit on Ante concerning multi-threading and RAII please?

**Comment by jfecher** [comment]
Sure.  Ante does not have a multithreading library even in the design phase.  There will be support in the future, but this especially is a topic that I feel requires extensive research.  I do not consider the channels go has implemented to be adequate since they do not prevent deadlocks or race conditions.  A key design principle in Ante is that not only should something be extensible, it should be _easy_.  Dealing with race conditions is not easy.

I am looking into how rust handles this problem and if that is adequate then concurrency support may be intertwined with the upcoming `Ownership` module.  One possible design is if Ownership is not imported then only do ownership-tracing for values sent between threads and if it is imported, do it for all values.

Multithreading will not have first class support but will most likely be implemented with a module with several ante functions that will implement new features in the language if necessary.

RAII is planned and mostly implemented already.  The only real work that needs to be done is implementing a default destructor for values whose fields have destructors.

Thank you for your interest in this project, hopefully these features will be implemented quickly, although the reality is they will probably take some time.

**Comment by codec-abc** [comment]
Thanks again! I am really glad you have some thought about all those topics. Really looking forward to this.

**Comment by codec-abc** [comment]
Maybe I have closed it a bit prematurely. Do you want that I leave it open so it reminds you to upload your few code samples?

**Comment by jfecher** [comment]
Closing it is fine, I'll remember
