### ISSUE TITLE
match expression fails to assign variables when there are no constructors to match against

### ISSUE THREAD

**Issue by andyjansson** [jfecher/ante#80]
Ante does not assign `x` in the following scenario:

```
match foo with
| x -> x
```

The reason for this being that variable binding information is carried by the [`fields` property](https://github.com/jfecher/ante/blob/master/src/types/pattern.rs#L747) on the `Case` struct, but a [`Leaf`](https://github.com/jfecher/ante/blob/master/src/types/pattern.rs#L726) is produced straight away so we lose this information. 

The possible solutions that come to mind include: 
* Having `Leaf` carry variable binding information.
* Treating this scenario as a let expression. 
* Disallowing `match` expressions with only one case. 
* Changing the decision tree to communicate the variable binding data some other way (e.g. by an explicit node).

**Comment by jfecher** [comment]
Finally got around to fixing this. The fix for now is a bit hacky: there's an explicit check for match statements in this form and if one is found we represent it as `x = foo; x` instead. In the future if ante gets an explicit Block node we can use it to better control the scope of any variables declared in this sequence expression but for now any variables leaked outside of the match branch scope aren't a soundness issue since the branch is always matched.
